baseurl = "https://uuoofan.github.io/"
title = "午飯網絡日誌"
author = "UUoo Fan"
relativeurls = true
canonifyurls = true
languagecode = "en"
paginate = 3
theme = "hugo-renga"

enableEmoji = true
hasCJKLanguage = true

googleAnalytics = "UA-98330599-2"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    blog = ":year/:month/:day/:slug/"

[params]
pagetitle = "午飯網絡日誌"
copyright = "© 2010 -- 2019 UUoo Fan"
copyrightUrl = "https://uuoofan.github.io/"
faviconfile = "image/fan.png"
logofile = "image/fan.png"
posts_navigation = true
uselatex = true
highlightjs = true
progressively = false

github = "uuoofan"
email = "uuoofan@gmail.com"

[[menu.primary]]
identifier = "about"
name = "本人"
url = "/about/"
weight = 10

[[menu.primary]]
identifier = "blog"
name = "日誌"
url = "/blog/"
weight = 2
